[package]
name = "nn"
version = "0.1.0"
authors = ["mariusdanciu <marius.danciu@ro.ibm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.12"
rand = "0.7.2"

